global:
  scrape_interval: 5s

scrape_configs:
  
  - job_name: "gitlab_server"
    metrics_path: "/-/metrics"
    static_configs:
      - targets: ["gitlab:80"]

  - job_name: "gitlab_redis"
    static_configs:
      - targets: ["gitlab:9121"]

  - job_name: "gitlab_postgres"
    static_configs:
      - targets: ["gitlab:9187"]

  - job_name: "gitlab_workhorse"
    static_configs:
      - targets: ["gitlab:9229"]

  - job_name: gitlab_sidekiq
    static_configs:
      - targets: ["gitlab:8082"]

  - job_name: gitlab_exporter_database
    metrics_path: "/database"
    static_configs:
      - targets: ["gitlab:9168"]

  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
      - targets: ["gitlab:9168"]

  - job_name: gitlab_gitaly
    static_configs:
      - targets: ["gitlab:9236"]
  
  - job_name: registry
    static_configs:
      - targets: ["gitlab:5001"]

  - job_name: 'cadvisor_exporter'
    static_configs:
    - targets: ['cadvisor_exporter:8080']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'gitlab_ci_pipeline_exporter'
    static_configs:
      - targets: ['gitlab_ci_pipeline_exporter:8080']

  - job_name: 'blackbox_exporter'
    metrics_path: "/probe"
    params:
      module: ["http_2xx"]
    static_configs:
      - targets: ["gitlab:80", "cadvisor_exporter:8080"]
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox:9115
