global:
  scrape_interval: 5s

scrape_configs:
  
  - job_name: "gitlab_server"
    metrics_path: "/-/metrics"
    static_configs:
      - targets: ["gitlab:80"]

  - job_name: 'cadvisor_exporter'
    static_configs:
    - targets: ['cadvisor_exporter:8080']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'gitlab_ci_pipeline_exporter'
    static_configs:
      - targets: ['gitlab_ci_pipeline_exporter:8080']
